<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>FitOSC</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.Hosting" />
        <Using Include="Microsoft.Extensions.Logging" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="LucHeart.CoreOSC" Version="1.4.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
        <PackageReference Include="OscQueryLibrary" Version="1.1.1" />
    </ItemGroup>
</Project>
