<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <OutputType>WinExe</OutputType>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PackageIcon>icon.ico</PackageIcon>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishSingleFile>true</PublishSingleFile>
        <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
        <Version>2.1.0</Version>
    </PropertyGroup>
    <PropertyGroup>
        <ServerGarbageCollection>false</ServerGarbageCollection>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="DawnCache\**"/>
        <Compile Remove="GPUCache\**"/>
        <Content Remove="DawnCache\**"/>
        <Content Remove="GPUCache\**"/>
        <EmbeddedResource Remove="DawnCache\**"/>
        <EmbeddedResource Remove="GPUCache\**"/>
        <None Remove="DawnCache\**"/>
        <None Remove="GPUCache\**"/>
        <Compile Update="App.axaml.cs">
            <DependentUpon>App.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Client\Views\ClientWindow.axaml.cs">
            <DependentUpon>ClientWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Content Update="wwwroot\fonts\brush-script-mt.ttf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\js\three.min.js">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\js\treadmillDisplay.js">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="LucHeart.CoreOSC" Version="1.4.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="10.0.110"/>

        <PackageReference Include="Avalonia" Version="11.1.4"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.1.4"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.4"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.4"/>
        <PackageReference Include="Avalonia.Themes.Simple" Version="11.1.4"/>
        <PackageReference Include="NAudio.Midi" Version="2.2.1" />
        <PackageReference Include="OscQueryLibrary" Version="1.1.1" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
        <TrimmableAssembly Include="Avalonia.Themes.Fluent"/>
        <TrimmableAssembly Include="Avalonia.Themes.Default"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.4"/>
    </ItemGroup>
    <ItemGroup>
        <ContentWithTargetPath Include="OpenVR\openvr_api.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>openvr_api.dll</TargetPath>
        </ContentWithTargetPath>
    </ItemGroup>
    <ItemGroup>
        <Content Update="SteamVR\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <None Remove="Assets\icon.ico" />
      <AvaloniaResource Include="Assets\icon.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </AvaloniaResource>
    </ItemGroup>
</Project>
